### ISSUE TITLE
No flash fails with only <object>

### ISSUE THREAD

**Issue by hfiguiere** [hfiguiere/no-flash#37]
On this page, no-flash doesn't fix the youtube embed.

http://www.ratp.fr/fr/ratp/r_61654/paris-visite/

**Comment by hfiguiere** [comment]
Because there is no ````<embed>```` just a ````<object>````

**Comment by hfiguiere** [comment]
Another example.
http://www.studio09.net/index.php?option=com_content&view=category&layout=blog&id=41&Itemid=43

**Comment by hfiguiere** [comment]
We can try to get the ```<object>``` elements after replacing the embeds. And make sure they are not in an ```<embed>```.

**Comment by frictionel** [comment]
The VOTD.tv blog is using a lot of this code. :(

http://votd.tv/blog/25/ohh-bowie-r-i-p

**Comment by hfiguiere** [comment]
And these are from vimeo... :-/

**Comment by hfiguiere** [comment]
Good news, I have a pending patch to fix this.
