### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by hfiguiere** [hfiguiere/no-flash#39]
Use the new WebExtensions API.

**Comment by ssokolow** [comment]
This is a bit of a pressing concern, given that Firefox 57 will disable support for XUL extensions.

If nothing else, now is the time to double-check that the WebExtensions APIs offered are sufficient, so there's still time to file feature requests and have them go through design and implementation before Firefox 57 enters Aurora channel in August.

**Comment by hfiguiere** [comment]
This is not a XUL extension. It uses the Add-on SDK (né Jetpack). I believe the porting effort might be minimal but it is my understanding that using the SDK this way is safe.

**Comment by ssokolow** [comment]
The way I'd heard it, Firefox 57 will refuse to run anything that isn't a WebExtension. Do you have a source for your interpretation?

(I was using "XUL extensions" to include the Add-on SDK because, before it was bundled with Firefox, it was just an abstraction library you had to bundle into your XPI yourself.)

**Comment by hfiguiere** [comment]
Most of no-flash features, ie rewriting YouTube Flash embed, are now in Firefox. (I didn't take any part in this)

**Comment by ssokolow** [comment]
That's good to hear.

As long as I don't experience any disruption when Firefox 57 rolls around, I'll be happy.

**Comment by ssokolow** [comment]
For the record, I just confirmed. The [latest Mozilla communication I'm aware of](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) says as follows:

> Firefox 57, November 14th release
>
>    Firefox will only run WebExtensions.

**Comment by gerv** [comment]
@hfiguiere: are you saying that this extension is no longer necessary because most of its functionality is built into Firefox?

**Comment by hfiguiere** [comment]
There are many cases where the Firefox embed rewrite do not work. 

But at the moment this extension no longer do anything because it no longer get the event ```PluginBindingAttached```. And I don't know yet how I can get an equivalent in the WebExtension API.

**Comment by hfiguiere** [comment]
Also it support Vimeo and and Daily Motion

**Comment by hfiguiere** [comment]
Current master works as a WebExtension.
